# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-12-17 19:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0009_auto_20181218_0006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='thumb',
            field=models.ImageField(default='media/pic_folder/None/no-img.jpg', upload_to='media/pic_folder/'),
        ),
    ]
